// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoginInput,
  RegisterCompleteInput,
  RegisterInput,
  ResetPasswordCompleteInput,
  ResetPasswordInput,
  ResponseRegisterPayloadAuthErrorCode,
  ResponseResetPasswordPayloadAuthErrorCode,
  ResponseTokenPayloadAuthErrorCode,
} from '../models/index';
import {
    LoginInputFromJSON,
    LoginInputToJSON,
    RegisterCompleteInputFromJSON,
    RegisterCompleteInputToJSON,
    RegisterInputFromJSON,
    RegisterInputToJSON,
    ResetPasswordCompleteInputFromJSON,
    ResetPasswordCompleteInputToJSON,
    ResetPasswordInputFromJSON,
    ResetPasswordInputToJSON,
    ResponseRegisterPayloadAuthErrorCodeFromJSON,
    ResponseRegisterPayloadAuthErrorCodeToJSON,
    ResponseResetPasswordPayloadAuthErrorCodeFromJSON,
    ResponseResetPasswordPayloadAuthErrorCodeToJSON,
    ResponseTokenPayloadAuthErrorCodeFromJSON,
    ResponseTokenPayloadAuthErrorCodeToJSON,
} from '../models/index';

export interface LoginRequest {
    loginInput: LoginInput;
}

export interface RegisterRequest {
    registerInput: RegisterInput;
}

export interface RegisterCompleteRequest {
    registerCompleteInput: RegisterCompleteInput;
}

export interface ResetPasswordRequest {
    resetPasswordInput: ResetPasswordInput;
}

export interface ResetPasswordCompleteRequest {
    resetPasswordCompleteInput: ResetPasswordCompleteInput;
}

/**
 * 
 */
export class AuthControllerApi extends runtime.BaseAPI {

    /**
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseTokenPayloadAuthErrorCode>> {
        if (requestParameters['loginInput'] == null) {
            throw new runtime.RequiredError(
                'loginInput',
                'Required parameter "loginInput" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginInputToJSON(requestParameters['loginInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseTokenPayloadAuthErrorCodeFromJSON(jsonValue));
    }

    /**
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseTokenPayloadAuthErrorCode> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseRegisterPayloadAuthErrorCode>> {
        if (requestParameters['registerInput'] == null) {
            throw new runtime.RequiredError(
                'registerInput',
                'Required parameter "registerInput" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterInputToJSON(requestParameters['registerInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseRegisterPayloadAuthErrorCodeFromJSON(jsonValue));
    }

    /**
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseRegisterPayloadAuthErrorCode> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async registerCompleteRaw(requestParameters: RegisterCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseTokenPayloadAuthErrorCode>> {
        if (requestParameters['registerCompleteInput'] == null) {
            throw new runtime.RequiredError(
                'registerCompleteInput',
                'Required parameter "registerCompleteInput" was null or undefined when calling registerComplete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register/complete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterCompleteInputToJSON(requestParameters['registerCompleteInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseTokenPayloadAuthErrorCodeFromJSON(jsonValue));
    }

    /**
     */
    async registerComplete(requestParameters: RegisterCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseTokenPayloadAuthErrorCode> {
        const response = await this.registerCompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async resetPasswordRaw(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseResetPasswordPayloadAuthErrorCode>> {
        if (requestParameters['resetPasswordInput'] == null) {
            throw new runtime.RequiredError(
                'resetPasswordInput',
                'Required parameter "resetPasswordInput" was null or undefined when calling resetPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/reset-password`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordInputToJSON(requestParameters['resetPasswordInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseResetPasswordPayloadAuthErrorCodeFromJSON(jsonValue));
    }

    /**
     */
    async resetPassword(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseResetPasswordPayloadAuthErrorCode> {
        const response = await this.resetPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async resetPasswordCompleteRaw(requestParameters: ResetPasswordCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseResetPasswordPayloadAuthErrorCode>> {
        if (requestParameters['resetPasswordCompleteInput'] == null) {
            throw new runtime.RequiredError(
                'resetPasswordCompleteInput',
                'Required parameter "resetPasswordCompleteInput" was null or undefined when calling resetPasswordComplete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/reset-password/complete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordCompleteInputToJSON(requestParameters['resetPasswordCompleteInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseResetPasswordPayloadAuthErrorCodeFromJSON(jsonValue));
    }

    /**
     */
    async resetPasswordComplete(requestParameters: ResetPasswordCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseResetPasswordPayloadAuthErrorCode> {
        const response = await this.resetPasswordCompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
