/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseSchoolSchoolErrorCode,
  SchoolUpdateInput,
} from '../models/index';
import {
    ResponseSchoolSchoolErrorCodeFromJSON,
    ResponseSchoolSchoolErrorCodeToJSON,
    SchoolUpdateInputFromJSON,
    SchoolUpdateInputToJSON,
} from '../models/index';

export interface UpdateRequest {
    schoolUpdateInput: SchoolUpdateInput;
}

/**
 * 
 */
export class SchoolControllerApi extends runtime.BaseAPI {

    /**
     */
    async getRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchoolSchoolErrorCode>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/school`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchoolSchoolErrorCodeFromJSON(jsonValue));
    }

    /**
     */
    async get(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchoolSchoolErrorCode> {
        const response = await this.getRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateRaw(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchoolSchoolErrorCode>> {
        if (requestParameters['schoolUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'schoolUpdateInput',
                'Required parameter "schoolUpdateInput" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/school`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SchoolUpdateInputToJSON(requestParameters['schoolUpdateInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchoolSchoolErrorCodeFromJSON(jsonValue));
    }

    /**
     */
    async update(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchoolSchoolErrorCode> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
