/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PageResponseTeacherObject,
} from '../models/index';
import {
    PageResponseTeacherObjectFromJSON,
    PageResponseTeacherObjectToJSON,
} from '../models/index';

export interface GetTeachersRequest {
    limit: number;
    offset: number;
}

/**
 * 
 */
export class TeacherControllerApi extends runtime.BaseAPI {

    /**
     */
    async getTeachersRaw(requestParameters: GetTeachersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageResponseTeacherObject>> {
        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling getTeachers().'
            );
        }

        if (requestParameters['offset'] == null) {
            throw new runtime.RequiredError(
                'offset',
                'Required parameter "offset" was null or undefined when calling getTeachers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/teachers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageResponseTeacherObjectFromJSON(jsonValue));
    }

    /**
     */
    async getTeachers(requestParameters: GetTeachersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageResponseTeacherObject> {
        const response = await this.getTeachersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
