// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentExportInput
 */
export interface DocumentExportInput {
    /**
     * 
     * @type {string}
     * @memberof DocumentExportInput
     */
    name: string;
}

/**
 * Check if a given object implements the DocumentExportInput interface.
 */
export function instanceOfDocumentExportInput(value: object): value is DocumentExportInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DocumentExportInputFromJSON(json: any): DocumentExportInput {
    return DocumentExportInputFromJSONTyped(json, false);
}

export function DocumentExportInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentExportInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function DocumentExportInputToJSON(value?: DocumentExportInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

