// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentUpdateInputTime
 */
export interface DocumentUpdateInputTime {
    /**
     * 
     * @type {number}
     * @memberof DocumentUpdateInputTime
     */
    year?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentUpdateInputTime
     */
    month?: DocumentUpdateInputTimeMonthEnum;
    /**
     * 
     * @type {number}
     * @memberof DocumentUpdateInputTime
     */
    monthValue?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentUpdateInputTime
     */
    leapYear?: boolean;
}


/**
 * @export
 */
export const DocumentUpdateInputTimeMonthEnum = {
    January: 'JANUARY',
    February: 'FEBRUARY',
    March: 'MARCH',
    April: 'APRIL',
    May: 'MAY',
    June: 'JUNE',
    July: 'JULY',
    August: 'AUGUST',
    September: 'SEPTEMBER',
    October: 'OCTOBER',
    November: 'NOVEMBER',
    December: 'DECEMBER'
} as const;
export type DocumentUpdateInputTimeMonthEnum = typeof DocumentUpdateInputTimeMonthEnum[keyof typeof DocumentUpdateInputTimeMonthEnum];


/**
 * Check if a given object implements the DocumentUpdateInputTime interface.
 */
export function instanceOfDocumentUpdateInputTime(value: object): value is DocumentUpdateInputTime {
    return true;
}

export function DocumentUpdateInputTimeFromJSON(json: any): DocumentUpdateInputTime {
    return DocumentUpdateInputTimeFromJSONTyped(json, false);
}

export function DocumentUpdateInputTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentUpdateInputTime {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'monthValue': json['monthValue'] == null ? undefined : json['monthValue'],
        'leapYear': json['leapYear'] == null ? undefined : json['leapYear'],
    };
}

export function DocumentUpdateInputTimeToJSON(value?: DocumentUpdateInputTime | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'year': value['year'],
        'month': value['month'],
        'monthValue': value['monthValue'],
        'leapYear': value['leapYear'],
    };
}

