// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentUpdatePayload
 */
export interface DocumentUpdatePayload {
    /**
     * 
     * @type {boolean}
     * @memberof DocumentUpdatePayload
     */
    success: boolean;
}

/**
 * Check if a given object implements the DocumentUpdatePayload interface.
 */
export function instanceOfDocumentUpdatePayload(value: object): value is DocumentUpdatePayload {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function DocumentUpdatePayloadFromJSON(json: any): DocumentUpdatePayload {
    return DocumentUpdatePayloadFromJSONTyped(json, false);
}

export function DocumentUpdatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentUpdatePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function DocumentUpdatePayloadToJSON(value?: DocumentUpdatePayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

