// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportDownloadPayload
 */
export interface ExportDownloadPayload {
    /**
     * 
     * @type {string}
     * @memberof ExportDownloadPayload
     */
    url: string;
}

/**
 * Check if a given object implements the ExportDownloadPayload interface.
 */
export function instanceOfExportDownloadPayload(value: object): value is ExportDownloadPayload {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ExportDownloadPayloadFromJSON(json: any): ExportDownloadPayload {
    return ExportDownloadPayloadFromJSONTyped(json, false);
}

export function ExportDownloadPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportDownloadPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function ExportDownloadPayloadToJSON(value?: ExportDownloadPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

