// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportDeleteInput
 */
export interface ExportDeleteInput {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExportDeleteInput
     */
    ids: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ExportDeleteInput
     */
    type?: ExportDeleteInputTypeEnum;
}


/**
 * @export
 */
export const ExportDeleteInputTypeEnum = {
    Include: 'INCLUDE',
    Exclude: 'EXCLUDE'
} as const;
export type ExportDeleteInputTypeEnum = typeof ExportDeleteInputTypeEnum[keyof typeof ExportDeleteInputTypeEnum];


/**
 * Check if a given object implements the ExportDeleteInput interface.
 */
export function instanceOfExportDeleteInput(value: object): value is ExportDeleteInput {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function ExportDeleteInputFromJSON(json: any): ExportDeleteInput {
    return ExportDeleteInputFromJSONTyped(json, false);
}

export function ExportDeleteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportDeleteInput {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ExportDeleteInputToJSON(value?: ExportDeleteInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ids': value['ids'],
        'type': value['type'],
    };
}

