// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportNameUpdateInput
 */
export interface ExportNameUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof ExportNameUpdateInput
     */
    name: string;
}

/**
 * Check if a given object implements the ExportNameUpdateInput interface.
 */
export function instanceOfExportNameUpdateInput(value: object): value is ExportNameUpdateInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ExportNameUpdateInputFromJSON(json: any): ExportNameUpdateInput {
    return ExportNameUpdateInputFromJSONTyped(json, false);
}

export function ExportNameUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportNameUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ExportNameUpdateInputToJSON(value?: ExportNameUpdateInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

