// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageMeta
 */
export interface PageMeta {
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    total: number;
}

/**
 * Check if a given object implements the PageMeta interface.
 */
export function instanceOfPageMeta(value: object): value is PageMeta {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PageMetaFromJSON(json: any): PageMeta {
    return PageMetaFromJSONTyped(json, false);
}

export function PageMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'total': json['total'],
    };
}

export function PageMetaToJSON(value?: PageMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'size': value['size'],
        'total': value['total'],
    };
}

