// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordUpdateTeacherDTO
 */
export interface RecordUpdateTeacherDTO {
    /**
     * 
     * @type {string}
     * @memberof RecordUpdateTeacherDTO
     */
    teacher?: string;
}

/**
 * Check if a given object implements the RecordUpdateTeacherDTO interface.
 */
export function instanceOfRecordUpdateTeacherDTO(value: object): value is RecordUpdateTeacherDTO {
    return true;
}

export function RecordUpdateTeacherDTOFromJSON(json: any): RecordUpdateTeacherDTO {
    return RecordUpdateTeacherDTOFromJSONTyped(json, false);
}

export function RecordUpdateTeacherDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordUpdateTeacherDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'teacher': json['teacher'] == null ? undefined : json['teacher'],
    };
}

export function RecordUpdateTeacherDTOToJSON(value?: RecordUpdateTeacherDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teacher': value['teacher'],
    };
}

