// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordUpdateHoursInput
 */
export interface RecordUpdateHoursInput {
    /**
     * 
     * @type {Array<number>}
     * @memberof RecordUpdateHoursInput
     */
    hours: Array<number>;
}

/**
 * Check if a given object implements the RecordUpdateHoursInput interface.
 */
export function instanceOfRecordUpdateHoursInput(value: object): value is RecordUpdateHoursInput {
    if (!('hours' in value) || value['hours'] === undefined) return false;
    return true;
}

export function RecordUpdateHoursInputFromJSON(json: any): RecordUpdateHoursInput {
    return RecordUpdateHoursInputFromJSONTyped(json, false);
}

export function RecordUpdateHoursInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordUpdateHoursInput {
    if (json == null) {
        return json;
    }
    return {
        
        'hours': json['hours'],
    };
}

export function RecordUpdateHoursInputToJSON(value?: RecordUpdateHoursInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hours': value['hours'],
    };
}

