// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordUpdateTypeDTO
 */
export interface RecordUpdateTypeDTO {
    /**
     * 
     * @type {string}
     * @memberof RecordUpdateTypeDTO
     */
    type?: RecordUpdateTypeDTOTypeEnum;
}


/**
 * @export
 */
export const RecordUpdateTypeDTOTypeEnum = {
    Course101: 'Course101',
    Course102: 'Course102',
    Course103: 'Course103',
    Course104: 'Course104',
    Course106: 'Course106',
    Course107: 'Course107',
    Course108: 'Course108',
    Course109: 'Course109',
    Course110: 'Course110',
    Course111: 'Course111',
    Course112: 'Course112',
    Course113: 'Course113',
    Course114: 'Course114',
    Course115: 'Course115',
    Course116: 'Course116',
    Course117: 'Course117',
    Course118: 'Course118',
    Course119: 'Course119',
    Course1070: 'Course1070',
    Course10700: 'Course10700',
    Course107000: 'Course107000',
    Course1070000: 'Course1070000',
    Course121: 'Course121',
    Course122: 'Course122',
    Course123: 'Course123',
    Course212: 'Course212'
} as const;
export type RecordUpdateTypeDTOTypeEnum = typeof RecordUpdateTypeDTOTypeEnum[keyof typeof RecordUpdateTypeDTOTypeEnum];


/**
 * Check if a given object implements the RecordUpdateTypeDTO interface.
 */
export function instanceOfRecordUpdateTypeDTO(value: object): value is RecordUpdateTypeDTO {
    return true;
}

export function RecordUpdateTypeDTOFromJSON(json: any): RecordUpdateTypeDTO {
    return RecordUpdateTypeDTOFromJSONTyped(json, false);
}

export function RecordUpdateTypeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordUpdateTypeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function RecordUpdateTypeDTOToJSON(value?: RecordUpdateTypeDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
    };
}

