// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Teacher } from './Teacher';
import {
    TeacherFromJSON,
    TeacherFromJSONTyped,
    TeacherToJSON,
} from './Teacher';

/**
 * 
 * @export
 * @interface Record
 */
export interface Record {
    /**
     * 
     * @type {number}
     * @memberof Record
     */
    line?: number;
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    type?: RecordTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    information?: string;
    /**
     * 
     * @type {Teacher}
     * @memberof Record
     */
    teacher?: Teacher;
}


/**
 * @export
 */
export const RecordTypeEnum = {
    Course101: 'Course101',
    Course102: 'Course102',
    Course103: 'Course103',
    Course104: 'Course104',
    Course106: 'Course106',
    Course107: 'Course107',
    Course108: 'Course108',
    Course109: 'Course109',
    Course110: 'Course110',
    Course111: 'Course111',
    Course112: 'Course112',
    Course113: 'Course113',
    Course114: 'Course114',
    Course115: 'Course115',
    Course116: 'Course116',
    Course117: 'Course117',
    Course118: 'Course118',
    Course119: 'Course119',
    Course1070: 'Course1070',
    Course10700: 'Course10700',
    Course107000: 'Course107000',
    Course1070000: 'Course1070000',
    Course121: 'Course121',
    Course122: 'Course122',
    Course123: 'Course123',
    Course212: 'Course212'
} as const;
export type RecordTypeEnum = typeof RecordTypeEnum[keyof typeof RecordTypeEnum];


/**
 * Check if a given object implements the Record interface.
 */
export function instanceOfRecord(value: object): value is Record {
    return true;
}

export function RecordFromJSON(json: any): Record {
    return RecordFromJSONTyped(json, false);
}

export function RecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): Record {
    if (json == null) {
        return json;
    }
    return {
        
        'line': json['line'] == null ? undefined : json['line'],
        'type': json['type'] == null ? undefined : json['type'],
        'information': json['information'] == null ? undefined : json['information'],
        'teacher': json['teacher'] == null ? undefined : TeacherFromJSON(json['teacher']),
    };
}

export function RecordToJSON(value?: Record | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'line': value['line'],
        'type': value['type'],
        'information': value['information'],
        'teacher': TeacherToJSON(value['teacher']),
    };
}

