// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordCreateInput
 */
export interface RecordCreateInput {
    /**
     * 
     * @type {string}
     * @memberof RecordCreateInput
     */
    previousId?: string;
    /**
     * 
     * @type {string}
     * @memberof RecordCreateInput
     */
    documentId: string;
    /**
     * 
     * @type {string}
     * @memberof RecordCreateInput
     */
    teacherId: string;
    /**
     * 
     * @type {string}
     * @memberof RecordCreateInput
     */
    type: RecordCreateInputTypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof RecordCreateInput
     */
    hours: Array<number>;
}


/**
 * @export
 */
export const RecordCreateInputTypeEnum = {
    Course101: 'Course101',
    Course102: 'Course102',
    Course103: 'Course103',
    Course104: 'Course104',
    Course106: 'Course106',
    Course107: 'Course107',
    Course108: 'Course108',
    Course109: 'Course109',
    Course110: 'Course110',
    Course111: 'Course111',
    Course112: 'Course112',
    Course113: 'Course113',
    Course114: 'Course114',
    Course115: 'Course115',
    Course116: 'Course116',
    Course117: 'Course117',
    Course118: 'Course118',
    Course119: 'Course119',
    Course1070: 'Course1070',
    Course10700: 'Course10700',
    Course107000: 'Course107000',
    Course1070000: 'Course1070000',
    Course121: 'Course121',
    Course122: 'Course122',
    Course123: 'Course123',
    Course212: 'Course212'
} as const;
export type RecordCreateInputTypeEnum = typeof RecordCreateInputTypeEnum[keyof typeof RecordCreateInputTypeEnum];


/**
 * Check if a given object implements the RecordCreateInput interface.
 */
export function instanceOfRecordCreateInput(value: object): value is RecordCreateInput {
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    if (!('teacherId' in value) || value['teacherId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('hours' in value) || value['hours'] === undefined) return false;
    return true;
}

export function RecordCreateInputFromJSON(json: any): RecordCreateInput {
    return RecordCreateInputFromJSONTyped(json, false);
}

export function RecordCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'previousId': json['previousId'] == null ? undefined : json['previousId'],
        'documentId': json['documentId'],
        'teacherId': json['teacherId'],
        'type': json['type'],
        'hours': json['hours'],
    };
}

export function RecordCreateInputToJSON(value?: RecordCreateInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'previousId': value['previousId'],
        'documentId': value['documentId'],
        'teacherId': value['teacherId'],
        'type': value['type'],
        'hours': value['hours'],
    };
}

