// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordUpdateInput
 */
export interface RecordUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof RecordUpdateInput
     */
    teacherId?: string;
    /**
     * 
     * @type {string}
     * @memberof RecordUpdateInput
     */
    type?: RecordUpdateInputTypeEnum;
}


/**
 * @export
 */
export const RecordUpdateInputTypeEnum = {
    Course101: 'Course101',
    Course102: 'Course102',
    Course103: 'Course103',
    Course104: 'Course104',
    Course106: 'Course106',
    Course107: 'Course107',
    Course108: 'Course108',
    Course109: 'Course109',
    Course110: 'Course110',
    Course111: 'Course111',
    Course112: 'Course112',
    Course113: 'Course113',
    Course114: 'Course114',
    Course115: 'Course115',
    Course116: 'Course116',
    Course117: 'Course117',
    Course118: 'Course118',
    Course119: 'Course119',
    Course1070: 'Course1070',
    Course10700: 'Course10700',
    Course107000: 'Course107000',
    Course1070000: 'Course1070000',
    Course121: 'Course121',
    Course122: 'Course122',
    Course123: 'Course123',
    Course212: 'Course212'
} as const;
export type RecordUpdateInputTypeEnum = typeof RecordUpdateInputTypeEnum[keyof typeof RecordUpdateInputTypeEnum];


/**
 * Check if a given object implements the RecordUpdateInput interface.
 */
export function instanceOfRecordUpdateInput(value: object): value is RecordUpdateInput {
    return true;
}

export function RecordUpdateInputFromJSON(json: any): RecordUpdateInput {
    return RecordUpdateInputFromJSONTyped(json, false);
}

export function RecordUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'teacherId': json['teacherId'] == null ? undefined : json['teacherId'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function RecordUpdateInputToJSON(value?: RecordUpdateInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teacherId': value['teacherId'],
        'type': value['type'],
    };
}

