// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordUpdateInformationDTO
 */
export interface RecordUpdateInformationDTO {
    /**
     * 
     * @type {string}
     * @memberof RecordUpdateInformationDTO
     */
    information?: string;
}

/**
 * Check if a given object implements the RecordUpdateInformationDTO interface.
 */
export function instanceOfRecordUpdateInformationDTO(value: object): value is RecordUpdateInformationDTO {
    return true;
}

export function RecordUpdateInformationDTOFromJSON(json: any): RecordUpdateInformationDTO {
    return RecordUpdateInformationDTOFromJSONTyped(json, false);
}

export function RecordUpdateInformationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordUpdateInformationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'information': json['information'] == null ? undefined : json['information'],
    };
}

export function RecordUpdateInformationDTOToJSON(value?: RecordUpdateInformationDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'information': value['information'],
    };
}

