/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterInput
 */
export interface RegisterInput {
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    schoolName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    principalName: string;
}

/**
 * Check if a given object implements the RegisterInput interface.
 */
export function instanceOfRegisterInput(value: object): value is RegisterInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('schoolName' in value) || value['schoolName'] === undefined) return false;
    if (!('principalName' in value) || value['principalName'] === undefined) return false;
    return true;
}

export function RegisterInputFromJSON(json: any): RegisterInput {
    return RegisterInputFromJSONTyped(json, false);
}

export function RegisterInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'title': json['title'],
        'password': json['password'],
        'schoolName': json['schoolName'],
        'principalName': json['principalName'],
    };
}

export function RegisterInputToJSON(value?: RegisterInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'title': value['title'],
        'password': value['password'],
        'schoolName': value['schoolName'],
        'principalName': value['principalName'],
    };
}

