// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterCompleteInput
 */
export interface RegisterCompleteInput {
    /**
     * 
     * @type {string}
     * @memberof RegisterCompleteInput
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompleteInput
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompleteInput
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompleteInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompleteInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompleteInput
     */
    schoolName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCompleteInput
     */
    principalName: string;
}

/**
 * Check if a given object implements the RegisterCompleteInput interface.
 */
export function instanceOfRegisterCompleteInput(value: object): value is RegisterCompleteInput {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('schoolName' in value) || value['schoolName'] === undefined) return false;
    if (!('principalName' in value) || value['principalName'] === undefined) return false;
    return true;
}

export function RegisterCompleteInputFromJSON(json: any): RegisterCompleteInput {
    return RegisterCompleteInputFromJSONTyped(json, false);
}

export function RegisterCompleteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterCompleteInput {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'token': json['token'],
        'title': json['title'],
        'password': json['password'],
        'schoolName': json['schoolName'],
        'principalName': json['principalName'],
    };
}

export function RegisterCompleteInputToJSON(value?: RegisterCompleteInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'token': value['token'],
        'title': value['title'],
        'password': value['password'],
        'schoolName': value['schoolName'],
        'principalName': value['principalName'],
    };
}

