// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordPayload
 */
export interface ResetPasswordPayload {
    /**
     * 
     * @type {boolean}
     * @memberof ResetPasswordPayload
     */
    success: boolean;
}

/**
 * Check if a given object implements the ResetPasswordPayload interface.
 */
export function instanceOfResetPasswordPayload(value: object): value is ResetPasswordPayload {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ResetPasswordPayloadFromJSON(json: any): ResetPasswordPayload {
    return ResetPasswordPayloadFromJSONTyped(json, false);
}

export function ResetPasswordPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function ResetPasswordPayloadToJSON(value?: ResetPasswordPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

