// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordCompleteInput
 */
export interface ResetPasswordCompleteInput {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordCompleteInput
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordCompleteInput
     */
    password: string;
}

/**
 * Check if a given object implements the ResetPasswordCompleteInput interface.
 */
export function instanceOfResetPasswordCompleteInput(value: object): value is ResetPasswordCompleteInput {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ResetPasswordCompleteInputFromJSON(json: any): ResetPasswordCompleteInput {
    return ResetPasswordCompleteInputFromJSONTyped(json, false);
}

export function ResetPasswordCompleteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordCompleteInput {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'password': json['password'],
    };
}

export function ResetPasswordCompleteInputToJSON(value?: ResetPasswordCompleteInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
        'password': value['password'],
    };
}

