// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseErrorUserErrorCode
 */
export interface ResponseErrorUserErrorCode {
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorUserErrorCode
     */
    code: ResponseErrorUserErrorCodeCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorUserErrorCode
     */
    message?: string;
}


/**
 * @export
 */
export const ResponseErrorUserErrorCodeCodeEnum = {
    UserNotFound: 'USER_NOT_FOUND',
    PasswordMismatch: 'PASSWORD_MISMATCH',
    UserEmailExists: 'USER_EMAIL_EXISTS'
} as const;
export type ResponseErrorUserErrorCodeCodeEnum = typeof ResponseErrorUserErrorCodeCodeEnum[keyof typeof ResponseErrorUserErrorCodeCodeEnum];


/**
 * Check if a given object implements the ResponseErrorUserErrorCode interface.
 */
export function instanceOfResponseErrorUserErrorCode(value: object): value is ResponseErrorUserErrorCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ResponseErrorUserErrorCodeFromJSON(json: any): ResponseErrorUserErrorCode {
    return ResponseErrorUserErrorCodeFromJSONTyped(json, false);
}

export function ResponseErrorUserErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseErrorUserErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponseErrorUserErrorCodeToJSON(value?: ResponseErrorUserErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

