/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseErrorAuthErrorCode } from './ResponseErrorAuthErrorCode';
import {
    ResponseErrorAuthErrorCodeFromJSON,
    ResponseErrorAuthErrorCodeFromJSONTyped,
    ResponseErrorAuthErrorCodeToJSON,
} from './ResponseErrorAuthErrorCode';
import type { TokenPayload } from './TokenPayload';
import {
    TokenPayloadFromJSON,
    TokenPayloadFromJSONTyped,
    TokenPayloadToJSON,
} from './TokenPayload';

/**
 * 
 * @export
 * @interface ResponseTokenPayloadAuthErrorCode
 */
export interface ResponseTokenPayloadAuthErrorCode {
    /**
     * 
     * @type {TokenPayload}
     * @memberof ResponseTokenPayloadAuthErrorCode
     */
    data?: TokenPayload;
    /**
     * 
     * @type {Array<ResponseErrorAuthErrorCode>}
     * @memberof ResponseTokenPayloadAuthErrorCode
     */
    errors?: Array<ResponseErrorAuthErrorCode>;
}

/**
 * Check if a given object implements the ResponseTokenPayloadAuthErrorCode interface.
 */
export function instanceOfResponseTokenPayloadAuthErrorCode(value: object): value is ResponseTokenPayloadAuthErrorCode {
    return true;
}

export function ResponseTokenPayloadAuthErrorCodeFromJSON(json: any): ResponseTokenPayloadAuthErrorCode {
    return ResponseTokenPayloadAuthErrorCodeFromJSONTyped(json, false);
}

export function ResponseTokenPayloadAuthErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseTokenPayloadAuthErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : TokenPayloadFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ResponseErrorAuthErrorCodeFromJSON)),
    };
}

export function ResponseTokenPayloadAuthErrorCodeToJSON(value?: ResponseTokenPayloadAuthErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': TokenPayloadToJSON(value['data']),
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ResponseErrorAuthErrorCodeToJSON)),
    };
}

