// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseErrorUserErrorCode } from './ResponseErrorUserErrorCode';
import {
    ResponseErrorUserErrorCodeFromJSON,
    ResponseErrorUserErrorCodeFromJSONTyped,
    ResponseErrorUserErrorCodeToJSON,
} from './ResponseErrorUserErrorCode';
import type { UserUpdatePasswordPayload } from './UserUpdatePasswordPayload';
import {
    UserUpdatePasswordPayloadFromJSON,
    UserUpdatePasswordPayloadFromJSONTyped,
    UserUpdatePasswordPayloadToJSON,
} from './UserUpdatePasswordPayload';

/**
 * 
 * @export
 * @interface ResponseUserUpdatePasswordPayloadUserErrorCode
 */
export interface ResponseUserUpdatePasswordPayloadUserErrorCode {
    /**
     * 
     * @type {UserUpdatePasswordPayload}
     * @memberof ResponseUserUpdatePasswordPayloadUserErrorCode
     */
    data?: UserUpdatePasswordPayload;
    /**
     * 
     * @type {Array<ResponseErrorUserErrorCode>}
     * @memberof ResponseUserUpdatePasswordPayloadUserErrorCode
     */
    errors: Array<ResponseErrorUserErrorCode>;
}

/**
 * Check if a given object implements the ResponseUserUpdatePasswordPayloadUserErrorCode interface.
 */
export function instanceOfResponseUserUpdatePasswordPayloadUserErrorCode(value: object): value is ResponseUserUpdatePasswordPayloadUserErrorCode {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ResponseUserUpdatePasswordPayloadUserErrorCodeFromJSON(json: any): ResponseUserUpdatePasswordPayloadUserErrorCode {
    return ResponseUserUpdatePasswordPayloadUserErrorCodeFromJSONTyped(json, false);
}

export function ResponseUserUpdatePasswordPayloadUserErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseUserUpdatePasswordPayloadUserErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : UserUpdatePasswordPayloadFromJSON(json['data']),
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorUserErrorCodeFromJSON)),
    };
}

export function ResponseUserUpdatePasswordPayloadUserErrorCodeToJSON(value?: ResponseUserUpdatePasswordPayloadUserErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': UserUpdatePasswordPayloadToJSON(value['data']),
        'errors': ((value['errors'] as Array<any>).map(ResponseErrorUserErrorCodeToJSON)),
    };
}

