// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseErrorDocumentErrorCode
 */
export interface ResponseErrorDocumentErrorCode {
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorDocumentErrorCode
     */
    code: ResponseErrorDocumentErrorCodeCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorDocumentErrorCode
     */
    message?: string;
}


/**
 * @export
 */
export const ResponseErrorDocumentErrorCodeCodeEnum = {
    DocumentNotFound: 'DOCUMENT_NOT_FOUND'
} as const;
export type ResponseErrorDocumentErrorCodeCodeEnum = typeof ResponseErrorDocumentErrorCodeCodeEnum[keyof typeof ResponseErrorDocumentErrorCodeCodeEnum];


/**
 * Check if a given object implements the ResponseErrorDocumentErrorCode interface.
 */
export function instanceOfResponseErrorDocumentErrorCode(value: object): value is ResponseErrorDocumentErrorCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ResponseErrorDocumentErrorCodeFromJSON(json: any): ResponseErrorDocumentErrorCode {
    return ResponseErrorDocumentErrorCodeFromJSONTyped(json, false);
}

export function ResponseErrorDocumentErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseErrorDocumentErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponseErrorDocumentErrorCodeToJSON(value?: ResponseErrorDocumentErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

