// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseErrorTeacherErrorCode
 */
export interface ResponseErrorTeacherErrorCode {
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorTeacherErrorCode
     */
    code: ResponseErrorTeacherErrorCodeCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorTeacherErrorCode
     */
    message?: string;
}


/**
 * @export
 */
export const ResponseErrorTeacherErrorCodeCodeEnum = {
    TeacherNotFound: 'TEACHER_NOT_FOUND'
} as const;
export type ResponseErrorTeacherErrorCodeCodeEnum = typeof ResponseErrorTeacherErrorCodeCodeEnum[keyof typeof ResponseErrorTeacherErrorCodeCodeEnum];


/**
 * Check if a given object implements the ResponseErrorTeacherErrorCode interface.
 */
export function instanceOfResponseErrorTeacherErrorCode(value: object): value is ResponseErrorTeacherErrorCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ResponseErrorTeacherErrorCodeFromJSON(json: any): ResponseErrorTeacherErrorCode {
    return ResponseErrorTeacherErrorCodeFromJSONTyped(json, false);
}

export function ResponseErrorTeacherErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseErrorTeacherErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponseErrorTeacherErrorCodeToJSON(value?: ResponseErrorTeacherErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

