// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseErrorAuthErrorCode } from './ResponseErrorAuthErrorCode';
import {
    ResponseErrorAuthErrorCodeFromJSON,
    ResponseErrorAuthErrorCodeFromJSONTyped,
    ResponseErrorAuthErrorCodeToJSON,
} from './ResponseErrorAuthErrorCode';
import type { TokenPayload } from './TokenPayload';
import {
    TokenPayloadFromJSON,
    TokenPayloadFromJSONTyped,
    TokenPayloadToJSON,
} from './TokenPayload';

/**
 * 
 * @export
 * @interface ResponseTokenPayloadAuthErrorCode
 */
export interface ResponseTokenPayloadAuthErrorCode {
    /**
     * 
     * @type {TokenPayload}
     * @memberof ResponseTokenPayloadAuthErrorCode
     */
    node?: TokenPayload;
    /**
     * 
     * @type {Array<ResponseErrorAuthErrorCode>}
     * @memberof ResponseTokenPayloadAuthErrorCode
     */
    errors: Array<ResponseErrorAuthErrorCode>;
}

/**
 * Check if a given object implements the ResponseTokenPayloadAuthErrorCode interface.
 */
export function instanceOfResponseTokenPayloadAuthErrorCode(value: object): value is ResponseTokenPayloadAuthErrorCode {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ResponseTokenPayloadAuthErrorCodeFromJSON(json: any): ResponseTokenPayloadAuthErrorCode {
    return ResponseTokenPayloadAuthErrorCodeFromJSONTyped(json, false);
}

export function ResponseTokenPayloadAuthErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseTokenPayloadAuthErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'] == null ? undefined : TokenPayloadFromJSON(json['node']),
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorAuthErrorCodeFromJSON)),
    };
}

export function ResponseTokenPayloadAuthErrorCodeToJSON(value?: ResponseTokenPayloadAuthErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'node': TokenPayloadToJSON(value['node']),
        'errors': ((value['errors'] as Array<any>).map(ResponseErrorAuthErrorCodeToJSON)),
    };
}

