// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseErrorDocumentErrorCode } from './ResponseErrorDocumentErrorCode';
import {
    ResponseErrorDocumentErrorCodeFromJSON,
    ResponseErrorDocumentErrorCodeFromJSONTyped,
    ResponseErrorDocumentErrorCodeToJSON,
} from './ResponseErrorDocumentErrorCode';
import type { Document } from './Document';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
} from './Document';

/**
 * 
 * @export
 * @interface ResponseDocumentDocumentErrorCode
 */
export interface ResponseDocumentDocumentErrorCode {
    /**
     * 
     * @type {Document}
     * @memberof ResponseDocumentDocumentErrorCode
     */
    data?: Document;
    /**
     * 
     * @type {Array<ResponseErrorDocumentErrorCode>}
     * @memberof ResponseDocumentDocumentErrorCode
     */
    errors: Array<ResponseErrorDocumentErrorCode>;
}

/**
 * Check if a given object implements the ResponseDocumentDocumentErrorCode interface.
 */
export function instanceOfResponseDocumentDocumentErrorCode(value: object): value is ResponseDocumentDocumentErrorCode {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ResponseDocumentDocumentErrorCodeFromJSON(json: any): ResponseDocumentDocumentErrorCode {
    return ResponseDocumentDocumentErrorCodeFromJSONTyped(json, false);
}

export function ResponseDocumentDocumentErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseDocumentDocumentErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DocumentFromJSON(json['data']),
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorDocumentErrorCodeFromJSON)),
    };
}

export function ResponseDocumentDocumentErrorCodeToJSON(value?: ResponseDocumentDocumentErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': DocumentToJSON(value['data']),
        'errors': ((value['errors'] as Array<any>).map(ResponseErrorDocumentErrorCodeToJSON)),
    };
}

