// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseErrorExportErrorCode
 */
export interface ResponseErrorExportErrorCode {
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorExportErrorCode
     */
    code: ResponseErrorExportErrorCodeCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorExportErrorCode
     */
    message?: string;
}


/**
 * @export
 */
export const ResponseErrorExportErrorCodeCodeEnum = {
    ExportNotFound: 'EXPORT_NOT_FOUND'
} as const;
export type ResponseErrorExportErrorCodeCodeEnum = typeof ResponseErrorExportErrorCodeCodeEnum[keyof typeof ResponseErrorExportErrorCodeCodeEnum];


/**
 * Check if a given object implements the ResponseErrorExportErrorCode interface.
 */
export function instanceOfResponseErrorExportErrorCode(value: object): value is ResponseErrorExportErrorCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ResponseErrorExportErrorCodeFromJSON(json: any): ResponseErrorExportErrorCode {
    return ResponseErrorExportErrorCodeFromJSONTyped(json, false);
}

export function ResponseErrorExportErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseErrorExportErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponseErrorExportErrorCodeToJSON(value?: ResponseErrorExportErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

