// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentDeletePayload } from './DocumentDeletePayload';
import {
    DocumentDeletePayloadFromJSON,
    DocumentDeletePayloadFromJSONTyped,
    DocumentDeletePayloadToJSON,
} from './DocumentDeletePayload';
import type { ResponseErrorDocumentErrorCode } from './ResponseErrorDocumentErrorCode';
import {
    ResponseErrorDocumentErrorCodeFromJSON,
    ResponseErrorDocumentErrorCodeFromJSONTyped,
    ResponseErrorDocumentErrorCodeToJSON,
} from './ResponseErrorDocumentErrorCode';

/**
 * 
 * @export
 * @interface ResponseDocumentDeletePayloadDocumentErrorCode
 */
export interface ResponseDocumentDeletePayloadDocumentErrorCode {
    /**
     * 
     * @type {DocumentDeletePayload}
     * @memberof ResponseDocumentDeletePayloadDocumentErrorCode
     */
    data?: DocumentDeletePayload;
    /**
     * 
     * @type {Array<ResponseErrorDocumentErrorCode>}
     * @memberof ResponseDocumentDeletePayloadDocumentErrorCode
     */
    errors: Array<ResponseErrorDocumentErrorCode>;
}

/**
 * Check if a given object implements the ResponseDocumentDeletePayloadDocumentErrorCode interface.
 */
export function instanceOfResponseDocumentDeletePayloadDocumentErrorCode(value: object): value is ResponseDocumentDeletePayloadDocumentErrorCode {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ResponseDocumentDeletePayloadDocumentErrorCodeFromJSON(json: any): ResponseDocumentDeletePayloadDocumentErrorCode {
    return ResponseDocumentDeletePayloadDocumentErrorCodeFromJSONTyped(json, false);
}

export function ResponseDocumentDeletePayloadDocumentErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseDocumentDeletePayloadDocumentErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DocumentDeletePayloadFromJSON(json['data']),
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorDocumentErrorCodeFromJSON)),
    };
}

export function ResponseDocumentDeletePayloadDocumentErrorCodeToJSON(value?: ResponseDocumentDeletePayloadDocumentErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': DocumentDeletePayloadToJSON(value['data']),
        'errors': ((value['errors'] as Array<any>).map(ResponseErrorDocumentErrorCodeToJSON)),
    };
}

