// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseErrorAuthErrorCode } from './ResponseErrorAuthErrorCode';
import {
    ResponseErrorAuthErrorCodeFromJSON,
    ResponseErrorAuthErrorCodeFromJSONTyped,
    ResponseErrorAuthErrorCodeToJSON,
} from './ResponseErrorAuthErrorCode';
import type { UserChangePasswordPayload } from './UserChangePasswordPayload';
import {
    UserChangePasswordPayloadFromJSON,
    UserChangePasswordPayloadFromJSONTyped,
    UserChangePasswordPayloadToJSON,
} from './UserChangePasswordPayload';

/**
 * 
 * @export
 * @interface ResponseUserChangePasswordPayloadAuthErrorCode
 */
export interface ResponseUserChangePasswordPayloadAuthErrorCode {
    /**
     * 
     * @type {UserChangePasswordPayload}
     * @memberof ResponseUserChangePasswordPayloadAuthErrorCode
     */
    data?: UserChangePasswordPayload;
    /**
     * 
     * @type {Array<ResponseErrorAuthErrorCode>}
     * @memberof ResponseUserChangePasswordPayloadAuthErrorCode
     */
    errors: Array<ResponseErrorAuthErrorCode>;
}

/**
 * Check if a given object implements the ResponseUserChangePasswordPayloadAuthErrorCode interface.
 */
export function instanceOfResponseUserChangePasswordPayloadAuthErrorCode(value: object): value is ResponseUserChangePasswordPayloadAuthErrorCode {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ResponseUserChangePasswordPayloadAuthErrorCodeFromJSON(json: any): ResponseUserChangePasswordPayloadAuthErrorCode {
    return ResponseUserChangePasswordPayloadAuthErrorCodeFromJSONTyped(json, false);
}

export function ResponseUserChangePasswordPayloadAuthErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseUserChangePasswordPayloadAuthErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : UserChangePasswordPayloadFromJSON(json['data']),
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorAuthErrorCodeFromJSON)),
    };
}

export function ResponseUserChangePasswordPayloadAuthErrorCodeToJSON(value?: ResponseUserChangePasswordPayloadAuthErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': UserChangePasswordPayloadToJSON(value['data']),
        'errors': ((value['errors'] as Array<any>).map(ResponseErrorAuthErrorCodeToJSON)),
    };
}

