/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseErrorObject
 */
export interface ResponseErrorObject {
    /**
     * 
     * @type {object}
     * @memberof ResponseErrorObject
     */
    code: object;
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorObject
     */
    message?: string;
}

/**
 * Check if a given object implements the ResponseErrorObject interface.
 */
export function instanceOfResponseErrorObject(value: object): value is ResponseErrorObject {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ResponseErrorObjectFromJSON(json: any): ResponseErrorObject {
    return ResponseErrorObjectFromJSONTyped(json, false);
}

export function ResponseErrorObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseErrorObject {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponseErrorObjectToJSON(value?: ResponseErrorObject | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

