// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeacherDeletePayload } from './TeacherDeletePayload';
import {
    TeacherDeletePayloadFromJSON,
    TeacherDeletePayloadFromJSONTyped,
    TeacherDeletePayloadToJSON,
} from './TeacherDeletePayload';
import type { ResponseErrorTeacherErrorCode } from './ResponseErrorTeacherErrorCode';
import {
    ResponseErrorTeacherErrorCodeFromJSON,
    ResponseErrorTeacherErrorCodeFromJSONTyped,
    ResponseErrorTeacherErrorCodeToJSON,
} from './ResponseErrorTeacherErrorCode';

/**
 * 
 * @export
 * @interface ResponseTeacherDeletePayloadTeacherErrorCode
 */
export interface ResponseTeacherDeletePayloadTeacherErrorCode {
    /**
     * 
     * @type {TeacherDeletePayload}
     * @memberof ResponseTeacherDeletePayloadTeacherErrorCode
     */
    data?: TeacherDeletePayload;
    /**
     * 
     * @type {Array<ResponseErrorTeacherErrorCode>}
     * @memberof ResponseTeacherDeletePayloadTeacherErrorCode
     */
    errors: Array<ResponseErrorTeacherErrorCode>;
}

/**
 * Check if a given object implements the ResponseTeacherDeletePayloadTeacherErrorCode interface.
 */
export function instanceOfResponseTeacherDeletePayloadTeacherErrorCode(value: object): value is ResponseTeacherDeletePayloadTeacherErrorCode {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ResponseTeacherDeletePayloadTeacherErrorCodeFromJSON(json: any): ResponseTeacherDeletePayloadTeacherErrorCode {
    return ResponseTeacherDeletePayloadTeacherErrorCodeFromJSONTyped(json, false);
}

export function ResponseTeacherDeletePayloadTeacherErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseTeacherDeletePayloadTeacherErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : TeacherDeletePayloadFromJSON(json['data']),
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorTeacherErrorCodeFromJSON)),
    };
}

export function ResponseTeacherDeletePayloadTeacherErrorCodeToJSON(value?: ResponseTeacherDeletePayloadTeacherErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': TeacherDeletePayloadToJSON(value['data']),
        'errors': ((value['errors'] as Array<any>).map(ResponseErrorTeacherErrorCodeToJSON)),
    };
}

