// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExportDeletePayload } from './ExportDeletePayload';
import {
    ExportDeletePayloadFromJSON,
    ExportDeletePayloadFromJSONTyped,
    ExportDeletePayloadToJSON,
} from './ExportDeletePayload';
import type { ResponseErrorExportErrorCode } from './ResponseErrorExportErrorCode';
import {
    ResponseErrorExportErrorCodeFromJSON,
    ResponseErrorExportErrorCodeFromJSONTyped,
    ResponseErrorExportErrorCodeToJSON,
} from './ResponseErrorExportErrorCode';

/**
 * 
 * @export
 * @interface ResponseExportDeletePayloadExportErrorCode
 */
export interface ResponseExportDeletePayloadExportErrorCode {
    /**
     * 
     * @type {ExportDeletePayload}
     * @memberof ResponseExportDeletePayloadExportErrorCode
     */
    data?: ExportDeletePayload;
    /**
     * 
     * @type {Array<ResponseErrorExportErrorCode>}
     * @memberof ResponseExportDeletePayloadExportErrorCode
     */
    errors: Array<ResponseErrorExportErrorCode>;
}

/**
 * Check if a given object implements the ResponseExportDeletePayloadExportErrorCode interface.
 */
export function instanceOfResponseExportDeletePayloadExportErrorCode(value: object): value is ResponseExportDeletePayloadExportErrorCode {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ResponseExportDeletePayloadExportErrorCodeFromJSON(json: any): ResponseExportDeletePayloadExportErrorCode {
    return ResponseExportDeletePayloadExportErrorCodeFromJSONTyped(json, false);
}

export function ResponseExportDeletePayloadExportErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseExportDeletePayloadExportErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ExportDeletePayloadFromJSON(json['data']),
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorExportErrorCodeFromJSON)),
    };
}

export function ResponseExportDeletePayloadExportErrorCodeToJSON(value?: ResponseExportDeletePayloadExportErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ExportDeletePayloadToJSON(value['data']),
        'errors': ((value['errors'] as Array<any>).map(ResponseErrorExportErrorCodeToJSON)),
    };
}

