// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseErrorRecordErrorCode } from './ResponseErrorRecordErrorCode';
import {
    ResponseErrorRecordErrorCodeFromJSON,
    ResponseErrorRecordErrorCodeFromJSONTyped,
    ResponseErrorRecordErrorCodeToJSON,
} from './ResponseErrorRecordErrorCode';
import type { Record } from './Record';
import {
    RecordFromJSON,
    RecordFromJSONTyped,
    RecordToJSON,
} from './Record';

/**
 * 
 * @export
 * @interface ResponseListRecordRecordErrorCode
 */
export interface ResponseListRecordRecordErrorCode {
    /**
     * 
     * @type {Array<Record>}
     * @memberof ResponseListRecordRecordErrorCode
     */
    node?: Array<Record>;
    /**
     * 
     * @type {Array<ResponseErrorRecordErrorCode>}
     * @memberof ResponseListRecordRecordErrorCode
     */
    errors: Array<ResponseErrorRecordErrorCode>;
}

/**
 * Check if a given object implements the ResponseListRecordRecordErrorCode interface.
 */
export function instanceOfResponseListRecordRecordErrorCode(value: object): value is ResponseListRecordRecordErrorCode {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ResponseListRecordRecordErrorCodeFromJSON(json: any): ResponseListRecordRecordErrorCode {
    return ResponseListRecordRecordErrorCodeFromJSONTyped(json, false);
}

export function ResponseListRecordRecordErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListRecordRecordErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'node': json['node'] == null ? undefined : ((json['node'] as Array<any>).map(RecordFromJSON)),
        'errors': ((json['errors'] as Array<any>).map(ResponseErrorRecordErrorCodeFromJSON)),
    };
}

export function ResponseListRecordRecordErrorCodeToJSON(value?: ResponseListRecordRecordErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'node': value['node'] == null ? undefined : ((value['node'] as Array<any>).map(RecordToJSON)),
        'errors': ((value['errors'] as Array<any>).map(ResponseErrorRecordErrorCodeToJSON)),
    };
}

