// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseErrorRecordErrorCode
 */
export interface ResponseErrorRecordErrorCode {
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorRecordErrorCode
     */
    code: ResponseErrorRecordErrorCodeCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseErrorRecordErrorCode
     */
    message?: string;
}


/**
 * @export
 */
export const ResponseErrorRecordErrorCodeCodeEnum = {
    RecordNotFound: 'RECORD_NOT_FOUND',
    TeacherNotFound: 'TEACHER_NOT_FOUND',
    DocumentNotFound: 'DOCUMENT_NOT_FOUND',
    RecordHoursTooLong: 'RECORD_HOURS_TOO_LONG'
} as const;
export type ResponseErrorRecordErrorCodeCodeEnum = typeof ResponseErrorRecordErrorCodeCodeEnum[keyof typeof ResponseErrorRecordErrorCodeCodeEnum];


/**
 * Check if a given object implements the ResponseErrorRecordErrorCode interface.
 */
export function instanceOfResponseErrorRecordErrorCode(value: object): value is ResponseErrorRecordErrorCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ResponseErrorRecordErrorCodeFromJSON(json: any): ResponseErrorRecordErrorCode {
    return ResponseErrorRecordErrorCodeFromJSONTyped(json, false);
}

export function ResponseErrorRecordErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseErrorRecordErrorCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResponseErrorRecordErrorCodeToJSON(value?: ResponseErrorRecordErrorCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

