// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeacherCreateInput
 */
export interface TeacherCreateInput {
    /**
     * 
     * @type {string}
     * @memberof TeacherCreateInput
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherCreateInput
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherCreateInput
     */
    branch: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherCreateInput
     */
    idNumber: string;
}

/**
 * Check if a given object implements the TeacherCreateInput interface.
 */
export function instanceOfTeacherCreateInput(value: object): value is TeacherCreateInput {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('branch' in value) || value['branch'] === undefined) return false;
    if (!('idNumber' in value) || value['idNumber'] === undefined) return false;
    return true;
}

export function TeacherCreateInputFromJSON(json: any): TeacherCreateInput {
    return TeacherCreateInputFromJSONTyped(json, false);
}

export function TeacherCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'branch': json['branch'],
        'idNumber': json['idNumber'],
    };
}

export function TeacherCreateInputToJSON(value?: TeacherCreateInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'branch': value['branch'],
        'idNumber': value['idNumber'],
    };
}

