// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeacherDeleteInput
 */
export interface TeacherDeleteInput {
    /**
     * 
     * @type {Array<string>}
     * @memberof TeacherDeleteInput
     */
    ids: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TeacherDeleteInput
     */
    type?: TeacherDeleteInputTypeEnum;
}


/**
 * @export
 */
export const TeacherDeleteInputTypeEnum = {
    Include: 'INCLUDE',
    Exclude: 'EXCLUDE'
} as const;
export type TeacherDeleteInputTypeEnum = typeof TeacherDeleteInputTypeEnum[keyof typeof TeacherDeleteInputTypeEnum];


/**
 * Check if a given object implements the TeacherDeleteInput interface.
 */
export function instanceOfTeacherDeleteInput(value: object): value is TeacherDeleteInput {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function TeacherDeleteInputFromJSON(json: any): TeacherDeleteInput {
    return TeacherDeleteInputFromJSONTyped(json, false);
}

export function TeacherDeleteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherDeleteInput {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function TeacherDeleteInputToJSON(value?: TeacherDeleteInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ids': value['ids'],
        'type': value['type'],
    };
}

