// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeacherUpdateInput
 */
export interface TeacherUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof TeacherUpdateInput
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherUpdateInput
     */
    branch?: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherUpdateInput
     */
    idNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof TeacherUpdateInput
     */
    description?: string;
}

/**
 * Check if a given object implements the TeacherUpdateInput interface.
 */
export function instanceOfTeacherUpdateInput(value: object): value is TeacherUpdateInput {
    return true;
}

export function TeacherUpdateInputFromJSON(json: any): TeacherUpdateInput {
    return TeacherUpdateInputFromJSONTyped(json, false);
}

export function TeacherUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'idNumber': json['idNumber'] == null ? undefined : json['idNumber'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TeacherUpdateInputToJSON(value?: TeacherUpdateInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'branch': value['branch'],
        'idNumber': value['idNumber'],
        'description': value['description'],
    };
}

