// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateNameInput
 */
export interface UserUpdateNameInput {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateNameInput
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateNameInput
     */
    lastName?: string;
}

/**
 * Check if a given object implements the UserUpdateNameInput interface.
 */
export function instanceOfUserUpdateNameInput(value: object): value is UserUpdateNameInput {
    return true;
}

export function UserUpdateNameInputFromJSON(json: any): UserUpdateNameInput {
    return UserUpdateNameInputFromJSONTyped(json, false);
}

export function UserUpdateNameInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateNameInput {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function UserUpdateNameInputToJSON(value?: UserUpdateNameInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

