// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateEmailInput
 */
export interface UserUpdateEmailInput {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateEmailInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateEmailInput
     */
    password: string;
}

/**
 * Check if a given object implements the UserUpdateEmailInput interface.
 */
export function instanceOfUserUpdateEmailInput(value: object): value is UserUpdateEmailInput {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserUpdateEmailInputFromJSON(json: any): UserUpdateEmailInput {
    return UserUpdateEmailInputFromJSONTyped(json, false);
}

export function UserUpdateEmailInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateEmailInput {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function UserUpdateEmailInputToJSON(value?: UserUpdateEmailInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

