// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdatePasswordInput
 */
export interface UserUpdatePasswordInput {
    /**
     * 
     * @type {string}
     * @memberof UserUpdatePasswordInput
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdatePasswordInput
     */
    newPassword: string;
}

/**
 * Check if a given object implements the UserUpdatePasswordInput interface.
 */
export function instanceOfUserUpdatePasswordInput(value: object): value is UserUpdatePasswordInput {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function UserUpdatePasswordInputFromJSON(json: any): UserUpdatePasswordInput {
    return UserUpdatePasswordInputFromJSONTyped(json, false);
}

export function UserUpdatePasswordInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdatePasswordInput {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'],
        'newPassword': json['newPassword'],
    };
}

export function UserUpdatePasswordInputToJSON(value?: UserUpdatePasswordInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
    };
}

