// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdatePasswordPayload
 */
export interface UserUpdatePasswordPayload {
    /**
     * 
     * @type {boolean}
     * @memberof UserUpdatePasswordPayload
     */
    success: boolean;
}

/**
 * Check if a given object implements the UserUpdatePasswordPayload interface.
 */
export function instanceOfUserUpdatePasswordPayload(value: object): value is UserUpdatePasswordPayload {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UserUpdatePasswordPayloadFromJSON(json: any): UserUpdatePasswordPayload {
    return UserUpdatePasswordPayloadFromJSONTyped(json, false);
}

export function UserUpdatePasswordPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdatePasswordPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function UserUpdatePasswordPayloadToJSON(value?: UserUpdatePasswordPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

