// @ts-nocheck

/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserChangePasswordPayload
 */
export interface UserChangePasswordPayload {
    /**
     * 
     * @type {boolean}
     * @memberof UserChangePasswordPayload
     */
    success: boolean;
}

/**
 * Check if a given object implements the UserChangePasswordPayload interface.
 */
export function instanceOfUserChangePasswordPayload(value: object): value is UserChangePasswordPayload {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UserChangePasswordPayloadFromJSON(json: any): UserChangePasswordPayload {
    return UserChangePasswordPayloadFromJSONTyped(json, false);
}

export function UserChangePasswordPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserChangePasswordPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function UserChangePasswordPayloadToJSON(value?: UserChangePasswordPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

