package com.incubator.edupayroll.configuration.controller;

public enum GlobalErrorCode {
  INVALID_JSON,
  INVALID_TYPE,
  ACCESS_DENIED,
  UNKNOWN_PROPERTY,
  NO_RESOURCE_FOUND,
  METHOD_NOT_ALLOWED,
  INVALID_CONSTRAINTS,
  INVALID_CREDENTIALS,
  INVALID_REQUEST_BODY,
  MISSING_REQUEST_PARAMETER,
}
